service: boost-api

provider:
  name: aws
  runtime: nodejs20.x
  stage: dev
  region: us-west-2
  environment:
    APP_VERSION: 0.1.1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:us-west-2:*:table/Boost.GitHub-App.installations"
    - Effect: "Allow"
      Action:
        - secretsmanager:GetSecretValue
      Resource: "arn:aws:secretsmanager:us-west-2:*:secret:*"

functions:
  api:
    handler: build/index.handler
    events:
      - httpApi: '*'
    url:
      invokeMode: RESPONSE_STREAM


plugins:
  - serverless-offline
